[book]
title = "Numbers Documentation"
src = "../docs"

[build]
build-dir = "build"

[output.html]
additional-css = ["theme/custom.css"]
additional-js = ["theme/force-dark.js"]
default-theme = "navy"
preferred-dark-theme = "navy"

